package com.example.demo.sql.entity;

import java.time.LocalDateTime;

public class Cow {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cow.id
     *
     * @mbggenerated Sat Jan 11 21:54:14 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cow.name
     *
     * @mbggenerated Sat Jan 11 21:54:14 CST 2020
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cow.old
     *
     * @mbggenerated Sat Jan 11 21:54:14 CST 2020
     */
    private Integer old;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cow.catch_time
     *
     * @mbggenerated Sat Jan 11 21:54:14 CST 2020
     */
    private LocalDateTime catchTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cow.weight
     *
     * @mbggenerated Sat Jan 11 21:54:14 CST 2020
     */
    private Double weight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cow.breed_status
     *
     * @mbggenerated Sat Jan 11 21:54:14 CST 2020
     */
    private String breedStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cow.is_heat
     *
     * @mbggenerated Sat Jan 11 21:54:14 CST 2020
     */
    private Boolean isHeat;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cow.id
     *
     * @return the value of cow.id
     *
     * @mbggenerated Sat Jan 11 21:54:14 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cow.id
     *
     * @param id the value for cow.id
     *
     * @mbggenerated Sat Jan 11 21:54:14 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cow.name
     *
     * @return the value of cow.name
     *
     * @mbggenerated Sat Jan 11 21:54:14 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cow.name
     *
     * @param name the value for cow.name
     *
     * @mbggenerated Sat Jan 11 21:54:14 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cow.old
     *
     * @return the value of cow.old
     *
     * @mbggenerated Sat Jan 11 21:54:14 CST 2020
     */
    public Integer getOld() {
        return old;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cow.old
     *
     * @param old the value for cow.old
     *
     * @mbggenerated Sat Jan 11 21:54:14 CST 2020
     */
    public void setOld(Integer old) {
        this.old = old;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cow.catch_time
     *
     * @return the value of cow.catch_time
     *
     * @mbggenerated Sat Jan 11 21:54:14 CST 2020
     */
    public LocalDateTime getCatchTime() {
        return catchTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cow.catch_time
     *
     * @param catchTime the value for cow.catch_time
     *
     * @mbggenerated Sat Jan 11 21:54:14 CST 2020
     */
    public void setCatchTime(LocalDateTime catchTime) {
        this.catchTime = catchTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cow.weight
     *
     * @return the value of cow.weight
     *
     * @mbggenerated Sat Jan 11 21:54:14 CST 2020
     */
    public Double getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cow.weight
     *
     * @param weight the value for cow.weight
     *
     * @mbggenerated Sat Jan 11 21:54:14 CST 2020
     */
    public void setWeight(Double weight) {
        this.weight = weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cow.breed_status
     *
     * @return the value of cow.breed_status
     *
     * @mbggenerated Sat Jan 11 21:54:14 CST 2020
     */
    public String getBreedStatus() {
        return breedStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cow.breed_status
     *
     * @param breedStatus the value for cow.breed_status
     *
     * @mbggenerated Sat Jan 11 21:54:14 CST 2020
     */
    public void setBreedStatus(String breedStatus) {
        this.breedStatus = breedStatus == null ? null : breedStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cow.is_heat
     *
     * @return the value of cow.is_heat
     *
     * @mbggenerated Sat Jan 11 21:54:14 CST 2020
     */
    public Boolean getIsHeat() {
        return isHeat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cow.is_heat
     *
     * @param isHeat the value for cow.is_heat
     *
     * @mbggenerated Sat Jan 11 21:54:14 CST 2020
     */
    public void setIsHeat(Boolean isHeat) {
        this.isHeat = isHeat;
    }
}