package com.example.demo.sql.entity;

import java.time.LocalDateTime;

public class TrueCowTemperature {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column true_cow_temperature.id
     *
     * @mbggenerated Sat Jan 11 21:54:14 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column true_cow_temperature.time
     *
     * @mbggenerated Sat Jan 11 21:54:14 CST 2020
     */
    private LocalDateTime time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column true_cow_temperature.value
     *
     * @mbggenerated Sat Jan 11 21:54:14 CST 2020
     */
    private Double value;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column true_cow_temperature.cow_id
     *
     * @mbggenerated Sat Jan 11 21:54:14 CST 2020
     */
    private Integer cowId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column true_cow_temperature.id
     *
     * @return the value of true_cow_temperature.id
     *
     * @mbggenerated Sat Jan 11 21:54:14 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column true_cow_temperature.id
     *
     * @param id the value for true_cow_temperature.id
     *
     * @mbggenerated Sat Jan 11 21:54:14 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column true_cow_temperature.time
     *
     * @return the value of true_cow_temperature.time
     *
     * @mbggenerated Sat Jan 11 21:54:14 CST 2020
     */
    public LocalDateTime getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column true_cow_temperature.time
     *
     * @param time the value for true_cow_temperature.time
     *
     * @mbggenerated Sat Jan 11 21:54:14 CST 2020
     */
    public void setTime(LocalDateTime time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column true_cow_temperature.value
     *
     * @return the value of true_cow_temperature.value
     *
     * @mbggenerated Sat Jan 11 21:54:14 CST 2020
     */
    public Double getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column true_cow_temperature.value
     *
     * @param value the value for true_cow_temperature.value
     *
     * @mbggenerated Sat Jan 11 21:54:14 CST 2020
     */
    public void setValue(Double value) {
        this.value = value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column true_cow_temperature.cow_id
     *
     * @return the value of true_cow_temperature.cow_id
     *
     * @mbggenerated Sat Jan 11 21:54:14 CST 2020
     */
    public Integer getCowId() {
        return cowId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column true_cow_temperature.cow_id
     *
     * @param cowId the value for true_cow_temperature.cow_id
     *
     * @mbggenerated Sat Jan 11 21:54:14 CST 2020
     */
    public void setCowId(Integer cowId) {
        this.cowId = cowId;
    }
}