package com.example.demo.sql.mapper;

import com.example.demo.sql.entity.Cow;
import com.example.demo.sql.entity.CowExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.session.RowBounds;

public interface CowMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cow
     *
     * @mbggenerated Sat Jan 11 21:54:14 CST 2020
     */
    int countByExample(CowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cow
     *
     * @mbggenerated Sat Jan 11 21:54:14 CST 2020
     */
    int deleteByExample(CowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cow
     *
     * @mbggenerated Sat Jan 11 21:54:14 CST 2020
     */
    @Delete({
        "delete from cow",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cow
     *
     * @mbggenerated Sat Jan 11 21:54:14 CST 2020
     */
    @Insert({
        "insert into cow (name, old, ",
        "catch_time, ",
        "weight, breed_status, ",
        "is_heat)",
        "values (#{name,jdbcType=VARCHAR}, #{old,jdbcType=INTEGER}, ",
        "#{catchTime,jdbcType=TIMESTAMP,typeHandler=org.apache.ibatis.type.LocalDateTimeTypeHandler}, ",
        "#{weight,jdbcType=DOUBLE}, #{breedStatus,jdbcType=VARCHAR}, ",
        "#{isHeat,jdbcType=BIT})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insert(Cow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cow
     *
     * @mbggenerated Sat Jan 11 21:54:14 CST 2020
     */
    int insertSelective(Cow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cow
     *
     * @mbggenerated Sat Jan 11 21:54:14 CST 2020
     */
    List<Cow> selectByExampleWithRowbounds(CowExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cow
     *
     * @mbggenerated Sat Jan 11 21:54:14 CST 2020
     */
    List<Cow> selectByExample(CowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cow
     *
     * @mbggenerated Sat Jan 11 21:54:14 CST 2020
     */
    @Select({
        "select",
        "id, name, old, catch_time, weight, breed_status, is_heat",
        "from cow",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    Cow selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cow
     *
     * @mbggenerated Sat Jan 11 21:54:14 CST 2020
     */
    int updateByExampleSelective(@Param("record") Cow record, @Param("example") CowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cow
     *
     * @mbggenerated Sat Jan 11 21:54:14 CST 2020
     */
    int updateByExample(@Param("record") Cow record, @Param("example") CowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cow
     *
     * @mbggenerated Sat Jan 11 21:54:14 CST 2020
     */
    int updateByPrimaryKeySelective(Cow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cow
     *
     * @mbggenerated Sat Jan 11 21:54:14 CST 2020
     */
    @Update({
        "update cow",
        "set name = #{name,jdbcType=VARCHAR},",
          "old = #{old,jdbcType=INTEGER},",
          "catch_time = #{catchTime,jdbcType=TIMESTAMP,typeHandler=org.apache.ibatis.type.LocalDateTimeTypeHandler},",
          "weight = #{weight,jdbcType=DOUBLE},",
          "breed_status = #{breedStatus,jdbcType=VARCHAR},",
          "is_heat = #{isHeat,jdbcType=BIT}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Cow record);
}